version: '3.8'
services:
  db:
    image: postgres:12.8-alpine
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local